# run: conda env create --file environment.yml
name: base
channels:
- defaults
- conda-forge
- rdkit
- matsci
dependencies:
- python
- anaconda
- jupyter
- numpy
- scipy
- pandas
- rdkit
- tensorflow
- keras
- pymatgen
- pip
- pip:
  - tqdm
  - keras_tqdm
